spring.application.name=Progetto-Coffee-cApp
server.port=8080


#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/coffee_app_db
#spring.datasource.username=root
#spring.datasource.password=1234567890


# URL di connessione
spring.datasource.url=jdbc:mysql://coffee-capp-132184a6-coffee-capp-0176.g.aivencloud.com:15746/coffee_app_db
# Credenziali di accesso
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_OuZduaX3vxn1_XlG49y


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
